### ISSUE TITLE
install_python failed on windows

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/lcm-pod#6]
had to commit a "if NOT WIN32" for the python support to get things working again on drake003.  
@rdeits - can you take a look?

**Comment by rdeits** [comment]
I can't even get LCM to build without the python extensions due to a bunch of missing "alloca.h" headers in glib. Is that something we know how to fix?

**Comment by RussTedrake** [comment]
turn on WITH_GTK, too.

**Comment by billhoffman** [comment]
I have a PR that is based on the cmake branch and fixed the build for me.  It sets https://github.com/RobotLocomotion/lcm-pod/pull/10
