### ISSUE TITLE
installing lcm-java fails (with probability??) on master on drake001 (old mac)

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/lcm-pod#7]
```
Making install in lcm-java
java.io.IOException: META-INF : could not create directory
        at sun.tools.jar.Main.extractFile(Main.java:995)
        at sun.tools.jar.Main.extract(Main.java:933)
        at sun.tools.jar.Main.run(Main.java:309)
        at sun.tools.jar.Main.main(Main.java:1233)
```

**Comment by RussTedrake** [comment]
this one is turning out to be a real pain on the build servers.  my best guess is that it's a race condition in the make logic in lcm.  if that's true, that would mean we could either (a) debug their autoconf setup, or (b) switch to using the cmake branch for everything.  I'm leaning towards (b) -- thought it might put more pressure on resolving #4.

what do others think?

**Comment by patmarion** [comment]
+1 for new cmake build and contributing it upstream.

I saw this error today when building lcm on the atlas machines.

**Comment by RussTedrake** [comment]
wow.  really good to know.  i had only seen it on drake001 (the mac).

**Comment by RussTedrake** [comment]
looking a little more (quickly), the most suspicious lines in the lcm-java/Makefile.am are in the jchart2d logic.  in particular, there is a dependency for a bunch of rules on the variable $(jchart2d_jar) which never actually gets set:
```
drake008% grep -R jchart2d_jar .
./lcm-java/Makefile:jar_DATA = $(JARFILE) $(jchart2d_jar)
./lcm-java/Makefile:$(JARFILE): $(jchart2d_jar) $(jide_extract) $(xmlgraphics_extract) classfiles
./lcm-java/Makefile.am:$(JARFILE): $(jchart2d_jar) $(jide_extract) $(xmlgraphics_extract) classfiles
./lcm-java/Makefile.am:jar_DATA = $(JARFILE) $(jchart2d_jar)
./lcm-java/Makefile.in:jar_DATA = $(JARFILE) $(jchart2d_jar)
./lcm-java/Makefile.in:$(JARFILE): $(jchart2d_jar) $(jide_extract) $(xmlgraphics_extract) classfiles
```

**Comment by andybarry** [comment]
That variable was added when Albert switched the build from Ant to autotools:

https://github.com/lcm-proj/lcm/commit/697c7decb813d4af88d27f1b3ab07aa9ebe43d81#diff-94f72b02f914fb6eb3ebce4fad8eb1b9L8


I agree, it doesn't seem to get set, so it ought to be empty and thus not modify the build.  I just tested building on my system without it and everything works.  So I think it's safe to remove, but don't see how it would cause the error we are seeing.

The error is in creating the META-INF directory, which sits inside lcm-java/build.  Can you tell if the "build" directory exists when you're getting this error?

**Comment by RussTedrake** [comment]
Really hard to tell.  It happens in a parallel build on the servers (though I believe i’ve seen it occasionally in the serial build, too).  Here is an example output:
http://drake001.csail.mit.edu/drake/pull-rdeits-rd-travis-into-RobotLocomotion-master <http://drake001.csail.mit.edu/drake/pull-rdeits-rd-travis-into-RobotLocomotion-master>

**Comment by RussTedrake** [comment]
this is not an issue in the cmake branch, so we believe it's a build logic error in the lcm makefiles.  closing.
